spring.application.name=Spring-Security

#spring.security.user.name:akshay
#spring.security.user.password:12345


spring.datasource.url=jdbc:mysql://localhost:3306/finflow_db
spring.datasource.username=root
spring.datasource.password=Akshay@754
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
